# Bifrost — split-horizon DNS daemon for LAN/Tailscale networks
#
# Home-manager module that:
#   1. Generates bifrost config from its own nodes/services options
#   2. Runs bifrost as a launchd agent (macOS) or systemd service (NixOS)
#   3. Writes dnsmasq overrides based on LAN reachability
#
# Topology data is set by the consumer (e.g., via a shared defaults module
# that reads from blackmatter.networkTopology at the system level).
#
{ hmHelpers, packages }:
{
  config,
  lib,
  pkgs,
  ...
}:
with lib; let
  cfg = config.services.bifrost;
  isDarwin = pkgs.stdenv.isDarwin;
  system = pkgs.stdenv.hostPlatform.system;

  inherit (hmHelpers) mkLaunchdService mkSystemdService;

  # Generate node entries: only nodes with tailscaleIpv4 and domains
  nodeLines = concatStringsSep "\n" (mapAttrsToList (name: node:
    if node.tailscaleIpv4 != null && node.domains != []
    then "node ${node.ipv4} ${node.tailscaleIpv4} ${concatStringsSep " " node.domains}"
    else "# ${name}: no tailscale IP, skipped"
  ) cfg.nodes);

  # Generate service entries: services always resolve to their LAN IP
  # (reachable via Tailscale subnet routing when remote)
  serviceLines = concatStringsSep "\n" (mapAttrsToList (name: svc:
    if svc.domains != []
    then "service ${svc.ipv4} ${concatStringsSep " " svc.domains}"
    else "# ${name}: no domains, skipped"
  ) cfg.services);

  # dnsmasq signal command differs by platform
  defaultSignalCmd = if isDarwin
    then "killall -HUP dnsmasq"
    else "systemctl reload dnsmasq";

  # dnsmasq config output path
  defaultConfPath = "/etc/dnsmasq.d/bifrost.conf";

  # Generated config file
  bifrostConfig = pkgs.writeText "bifrost.conf" ''
    # Bifrost config — generated by Nix, do not edit
    gateway ${cfg.gateway}
    probe-interval ${toString cfg.probeInterval}
    probe-timeout ${toString cfg.probeTimeout}
    dnsmasq-conf ${cfg.dnsmasqConf}
    dnsmasq-signal ${cfg.dnsmasqSignal}

    # Nodes (LAN IP → Tailscale IP → domains)
    ${nodeLines}

    # Services (LAN IPs, routed via Tailscale subnet when remote)
    ${serviceLines}
  '';

  logDir = if isDarwin
    then "${config.home.homeDirectory}/Library/Logs"
    else "${config.home.homeDirectory}/.local/share/bifrost/logs";

  # Submodule type for nodes
  nodeSubmodule = types.submodule {
    options = {
      ipv4 = mkOption {
        type = types.str;
        description = "LAN IPv4 address of the node";
      };
      tailscaleIpv4 = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "Tailscale IPv4 address (fallback when LAN unreachable)";
      };
      domains = mkOption {
        type = types.listOf types.str;
        default = [];
        description = "Domain names for this node";
      };
    };
  };

  # Submodule type for services
  serviceSubmodule = types.submodule {
    options = {
      ipv4 = mkOption {
        type = types.str;
        description = "IPv4 address of the service";
      };
      domains = mkOption {
        type = types.listOf types.str;
        default = [];
        description = "Domain names for this service";
      };
    };
  };
in {
  options.services.bifrost = {
    enable = mkEnableOption "Bifrost split-horizon DNS daemon";

    package = mkOption {
      type = types.package;
      default = packages.${system}.default;
      defaultText = literalExpression "bifrost.packages.\${system}.default";
      description = "Bifrost package";
    };

    gateway = mkOption {
      type = types.str;
      default = "192.168.50.1";
      description = "LAN gateway IP to probe for reachability";
    };

    probeInterval = mkOption {
      type = types.int;
      default = 10;
      description = "Seconds between gateway probes";
    };

    probeTimeout = mkOption {
      type = types.int;
      default = 1000;
      description = "Milliseconds to wait for gateway ping response";
    };

    dnsmasqConf = mkOption {
      type = types.str;
      default = defaultConfPath;
      description = "Path to write dnsmasq override config";
    };

    dnsmasqSignal = mkOption {
      type = types.str;
      default = defaultSignalCmd;
      description = "Command to reload dnsmasq after config update";
    };

    nodes = mkOption {
      type = types.attrsOf nodeSubmodule;
      default = {};
      description = ''
        Network nodes with LAN and optional Tailscale IPs.
        Bifrost switches between LAN and Tailscale IPs based on gateway reachability.
      '';
    };

    services = mkOption {
      type = types.attrsOf serviceSubmodule;
      default = {};
      description = ''
        Infrastructure services with LAN IPs.
        Always resolve to their LAN IP (reachable via Tailscale subnet routing when remote).
      '';
    };
  };

  config = mkMerge [
    # Darwin: launchd agent
    (mkIf (cfg.enable && isDarwin) (mkMerge [
      {
        home.activation.bifrost-dirs = lib.hm.dag.entryAfter ["writeBoundary"] ''
          run mkdir -p "${logDir}"
        '';
      }

      (mkLaunchdService {
        name = "bifrost";
        label = "io.pleme.bifrost";
        command = "${cfg.package}/bin/bifrost";
        args = ["daemon" "${bifrostConfig}"];
        logDir = logDir;
      })
    ]))

    # Linux: systemd user service
    (mkIf (cfg.enable && !isDarwin)
      (mkSystemdService {
        name = "bifrost";
        description = "Bifrost — split-horizon DNS for LAN/Tailscale";
        command = "${cfg.package}/bin/bifrost";
        args = ["daemon" "${bifrostConfig}"];
      }))
  ];
}
