# Bifrost — split-horizon DNS daemon for LAN/Tailscale networks
#
# Home-manager module that:
#   1. Generates bifrost config from blackmatter.networkTopology
#   2. Runs bifrost as a launchd agent (macOS) or systemd service (NixOS)
#   3. Writes dnsmasq overrides based on LAN reachability
#
# Requires: blackmatter.networkTopology with tailscaleIpv4 on nodes
#
{ hmHelpers, packages }:
{
  config,
  lib,
  pkgs,
  ...
}:
with lib; let
  cfg = config.services.bifrost;
  isDarwin = pkgs.stdenv.isDarwin;
  system = pkgs.stdenv.hostPlatform.system;

  inherit (hmHelpers) mkLaunchdService mkSystemdService;

  # Build the config file from network topology
  topoCfg = config.blackmatter.networkTopology;

  # Generate node entries: only nodes that have both lanIpv4 and tailscaleIpv4
  nodeLines = concatStringsSep "\n" (mapAttrsToList (name: node:
    if node ? tailscaleIpv4 && node.tailscaleIpv4 != null && node.domains != []
    then "node ${node.ipv4} ${node.tailscaleIpv4} ${concatStringsSep " " node.domains}"
    else "# ${name}: no tailscale IP, skipped"
  ) topoCfg.nodes);

  # Generate service entries: services always resolve to their LAN IP
  # (reachable via Tailscale subnet routing when remote)
  serviceLines = concatStringsSep "\n" (mapAttrsToList (name: svc:
    if svc.domains != []
    then "service ${svc.ipv4} ${concatStringsSep " " svc.domains}"
    else "# ${name}: no domains, skipped"
  ) topoCfg.services);

  # dnsmasq signal command differs by platform
  defaultSignalCmd = if isDarwin
    then "killall -HUP dnsmasq"
    else "systemctl reload dnsmasq";

  # dnsmasq config output path
  defaultConfPath = "/etc/dnsmasq.d/bifrost.conf";

  # Generated config file
  bifrostConfig = pkgs.writeText "bifrost.conf" ''
    # Bifrost config — generated by Nix, do not edit
    gateway ${cfg.gateway}
    probe-interval ${toString cfg.probeInterval}
    probe-timeout ${toString cfg.probeTimeout}
    dnsmasq-conf ${cfg.dnsmasqConf}
    dnsmasq-signal ${cfg.dnsmasqSignal}

    # Nodes (LAN IP → Tailscale IP → domains)
    ${nodeLines}

    # Services (LAN IPs, routed via Tailscale subnet when remote)
    ${serviceLines}
  '';

  logDir = if isDarwin
    then "${config.home.homeDirectory}/Library/Logs"
    else "${config.home.homeDirectory}/.local/share/bifrost/logs";
in {
  options.services.bifrost = {
    enable = mkEnableOption "Bifrost split-horizon DNS daemon";

    package = mkOption {
      type = types.package;
      default = packages.${system}.default;
      defaultText = literalExpression "bifrost.packages.\${system}.default";
      description = "Bifrost package";
    };

    gateway = mkOption {
      type = types.str;
      default = "192.168.50.1";
      description = "LAN gateway IP to probe for reachability";
    };

    probeInterval = mkOption {
      type = types.int;
      default = 10;
      description = "Seconds between gateway probes";
    };

    probeTimeout = mkOption {
      type = types.int;
      default = 1000;
      description = "Milliseconds to wait for gateway ping response";
    };

    dnsmasqConf = mkOption {
      type = types.str;
      default = defaultConfPath;
      description = "Path to write dnsmasq override config";
    };

    dnsmasqSignal = mkOption {
      type = types.str;
      default = defaultSignalCmd;
      description = "Command to reload dnsmasq after config update";
    };
  };

  config = mkMerge [
    # Darwin: launchd agent
    (mkIf (cfg.enable && isDarwin) (mkMerge [
      {
        home.activation.bifrost-dirs = lib.hm.dag.entryAfter ["writeBoundary"] ''
          run mkdir -p "${logDir}"
        '';
      }

      (mkLaunchdService {
        name = "bifrost";
        label = "io.pleme.bifrost";
        command = "${cfg.package}/bin/bifrost";
        args = ["daemon" "${bifrostConfig}"];
        logDir = logDir;
      })
    ]))

    # Linux: systemd user service
    (mkIf (cfg.enable && !isDarwin)
      (mkSystemdService {
        name = "bifrost";
        description = "Bifrost — split-horizon DNS for LAN/Tailscale";
        command = "${cfg.package}/bin/bifrost";
        args = ["daemon" "${bifrostConfig}"];
      }))
  ];
}
